# Generated by Django 6.0.1 on 2026-05-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tile', models.CharField(max_length=150)),
                ('File', models.FileField(upload_to='document/')),
                ('Description', models.TextField()),
            ],
        ),
    ]
